bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.6.0
  - ruby-head
  - ruby-head-clang
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
matrix:
  include:
    - gemfile: gemfiles/Gemfile.public_suffix_2
      rvm: 2.5.5
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: jruby-9.0.5.0
  fast_finish: true
before_install:
  - gem update bundler
addons:
  apt:
    packages:
    - libidn11-dev
